const champData = [
  // ** Group A **
  {
    name: 'Ajax',
    group: 'A',
    short_name: 'AJX',
    stadium: 'Amsterdam Arena',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Liverpool',
    group: 'A',
    short_name: 'LIV',
    stadium: 'Anfield',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Napoli',
    group: 'A',
    short_name: 'NAP',
    stadium: 'San Paolo',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Rangers FC',
    group: 'A',
    short_name: 'RAN',
    stadium: 'Ibrox Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group B **
  {
    name: 'Porto',
    group: 'B',
    short_name: 'POR',
    stadium: 'Estádio do Dragão',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Atletico Madrid',
    group: 'B',
    short_name: 'ATL',
    stadium: 'Metropolitano',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Bayer Leverkusen',
    group: 'B',
    short_name: 'LEV',
    stadium: 'BayArena',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Brugge',
    group: 'B',
    short_name: 'BRU',
    stadium: 'Jan Breydel Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group C **
  {
    name: 'Bayern München',
    group: 'C',
    short_name: 'BMU',
    stadium: 'Allianz Arena',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Barcelona',
    group: 'C',
    short_name: 'FCB',
    stadium: 'Spotify Camp Nou',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Inter Milan',
    group: 'C',
    short_name: 'INT',
    stadium: 'Giuseppe Meazza',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Viktoria Plzeň',
    group: 'C',
    short_name: 'PLZ',
    stadium: 'Doosan Arena',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group D **
  {
    name: 'Eintracht Frankfurt',
    group: 'D',
    short_name: 'FRA',
    stadium: 'Deutsche Bank Park',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Tottenham',
    group: 'D',
    short_name: 'TOT',
    stadium: 'Tottenham Hotspur Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Sporting Lisboa',
    group: 'D',
    short_name: 'LIS',
    stadium: 'Estádio José Alvalade',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Olympique de Marsella',
    group: 'D',
    short_name: 'MAR',
    stadium: 'Stade Vélodrome',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group E **
  {
    name: 'AC Milan',
    group: 'E',
    short_name: 'ACM',
    stadium: 'San Siro',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Chelsea',
    group: 'E',
    short_name: 'CHE',
    stadium: 'Stamford Bridge',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Salzburgo',
    group: 'E',
    short_name: 'SAL',
    stadium: 'Red Bull Arena de Salzburgo',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'GNK Dinamo Zagreb',
    group: 'E',
    short_name: 'DIN',
    stadium: 'Stadion Maksimir',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group F **
  {
    name: 'Real Madrid',
    group: 'F',
    short_name: 'RMA',
    stadium: 'Santiago Bernabéu',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Leipzig',
    group: 'F',
    short_name: 'LEI',
    stadium: 'Red Bull Arena',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Shakhtar Donetsk',
    group: 'F',
    short_name: 'SHA',
    stadium: 'Olímpico de Kiev',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Celtic',
    group: 'F',
    short_name: 'CEL',
    stadium: 'Celtic Park',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group G **
  {
    name: 'Manchester City',
    group: 'G',
    short_name: 'MCI',
    stadium: 'Etihad Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Sevilla',
    group: 'G',
    short_name: 'SEV',
    stadium: 'Ramón Sánchez-Pizjuán',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Borussia Dortmund',
    group: 'G',
    short_name: 'BVB',
    stadium: 'Signal Iduna Park',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: ' FC Copenhague',
    group: 'G',
    short_name: 'COP',
    stadium: 'Parken Stadion',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  // ** Group G **
  {
    name: 'Paris Saint-Germain',
    group: 'H',
    short_name: 'PSG',
    stadium: 'Parc des Princes',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Juventus',
    group: 'H',
    short_name: 'JUV',
    stadium: 'Juventus Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Benfica',
    group: 'H',
    short_name: 'BEN',
    stadium: 'Estádio da Luz',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
  {
    name: 'Maccabi Haifa',
    group: 'H',
    short_name: 'MAH',
    stadium: 'Sammy Ofer Stadium',
    p: 0,
    gf: 0,
    ga: 0,
    gd: 0,
    pts: 0,
  },
];

export default champData;
