var SECTIONS = {
  QAT: {title: 'QAT', file: require('../assets/flags/QAT.png')},
  ECU: {title: 'ECU', file: require('../assets/flags/ECU.png')},
  SEN: {title: 'SEN', file: require('../assets/flags/SEN.png')},
  NED: {title: 'NED', file: require('../assets/flags/NED.png')},
  ENG: {title: 'ENG', file: require('../assets/flags/ENG.png')},
  IRN: {title: 'IRN', file: require('../assets/flags/IRN.png')},
  USA: {title: 'USA', file: require('../assets/flags/USA.png')},
  WAL: {title: 'WAL', file: require('../assets/flags/WAL.png')},
  ARG: {title: 'ARG', file: require('../assets/flags/ARG.png')},
  KSA: {title: 'KSA', file: require('../assets/flags/KSA.png')},
  MEX: {title: 'MEX', file: require('../assets/flags/MEX.png')},
  POL: {title: 'POL', file: require('../assets/flags/POL.png')},
  FRA: {title: 'FRA', file: require('../assets/flags/FRA.png')},
  DEN: {title: 'DEN', file: require('../assets/flags/DEN.png')},
  TUN: {title: 'TUN', file: require('../assets/flags/TUN.png')},
  AUS: {title: 'AUS', file: require('../assets/flags/AUS.png')},
  ESP: {title: 'ESP', file: require('../assets/flags/ESP.png')},
  GER: {title: 'GER', file: require('../assets/flags/GER.png')},
  JPN: {title: 'JPN', file: require('../assets/flags/JPN.png')},
  CRC: {title: 'CRC', file: require('../assets/flags/CRC.png')},
  BEL: {title: 'BEL', file: require('../assets/flags/BEL.png')},
  CAN: {title: 'CAN', file: require('../assets/flags/CAN.png')},
  MAR: {title: 'MAR', file: require('../assets/flags/MAR.png')},
  CRO: {title: 'CRO', file: require('../assets/flags/CRO.png')},
  BRA: {title: 'BRA', file: require('../assets/flags/BRA.png')},
  SRB: {title: 'SRB', file: require('../assets/flags/SRB.png')},
  SUI: {title: 'SUI', file: require('../assets/flags/SUI.png')},
  CMR: {title: 'CMR', file: require('../assets/flags/CMR.png')},
  POR: {title: 'POR', file: require('../assets/flags/POR.png')},
  GHA: {title: 'GHA', file: require('../assets/flags/GHA.png')},
  URU: {title: 'URU', file: require('../assets/flags/URU.png')},
  KOR: {title: 'KOR', file: require('../assets/flags/KOR.png')},
};

export default SECTIONS;
