var CHAMPS = {
  ACM: {title: 'ACM', file: require('../assets/teams/ACM.png')},
  AJX: {title: 'AJX', file: require('../assets/teams/AJX.png')},
  ATL: {title: 'ATL', file: require('../assets/teams/ATL.png')},
  BEN: {title: 'BEN', file: require('../assets/teams/BEN.png')},
  BMU: {title: 'BMU', file: require('../assets/teams/BMU.png')},
  BRU: {title: 'BRU', file: require('../assets/teams/BRU.png')},
  BVB: {title: 'SEN', file: require('../assets/teams/BVB.png')},
  CEL: {title: 'CEL', file: require('../assets/teams/CEL.png')},
  CHE: {title: 'CHE', file: require('../assets/teams/CHE.png')},
  COP: {title: 'COP', file: require('../assets/teams/COP.png')},
  DIN: {title: 'DIN', file: require('../assets/teams/DIN.png')},
  FCB: {title: 'FCB', file: require('../assets/teams/FCB.png')},
  FRA: {title: 'FRA', file: require('../assets/teams/FRA.png')},
  INT: {title: 'INT', file: require('../assets/teams/INT.png')},
  JUV: {title: 'JUV', file: require('../assets/teams/JUV.png')},
  LEI: {title: 'LEI', file: require('../assets/teams/LEI.png')},
  LEV: {title: 'LEV', file: require('../assets/teams/LEV.png')},
  LIS: {title: 'LIS', file: require('../assets/teams/LIS.png')},
  LIV: {title: 'LIV', file: require('../assets/teams/LIV.png')},
  MAH: {title: 'MAH', file: require('../assets/teams/MAH.png')},
  MAR: {title: 'MAR', file: require('../assets/teams/MAR.png')},
  MCI: {title: 'MCI', file: require('../assets/teams/MCI.png')},
  NAP: {title: 'NAP', file: require('../assets/teams/NAP.png')},
  PLZ: {title: 'PLZ', file: require('../assets/teams/PLZ.png')},
  POR: {title: 'POR', file: require('../assets/teams/POR.png')},
  PSG: {title: 'PSG', file: require('../assets/teams/PSG.png')},
  RAN: {title: 'RAN', file: require('../assets/teams/RAN.png')},
  RMA: {title: 'RMA', file: require('../assets/teams/RMA.png')},
  SAL: {title: 'SAL', file: require('../assets/teams/SAL.png')},
  SEV: {title: 'SEV', file: require('../assets/teams/SEV.png')},
  SHA: {title: 'SHA', file: require('../assets/teams/SHA.png')},
  TOT: {title: 'TOT', file: require('../assets/teams/TOT.png')},
};

export default CHAMPS;
