const language = {
  EN: {
    cancel: 'Cancel',
    championMessage: 'Champion world cup Qatar 2022',
    chooseLang: 'Choose your language',
    close: 'Close',
    confirm: 'Confirm',
    confirmDelete: 'Yes, delete',
    confirmMessage: 'Are you sure you want to delete the data?',
    days: 'Days',
    delete: 'Delete',
    deletePlayground: 'Delete playground data',
    editing: 'Editing ',
    editPlayed: 'Edit Matches Played',
    endTime: 'End full time',
    errorChangeDay:
      'You will be able to change the day when you have saved all the results of the current day.',
    ga: 'GA',
    gd: 'GD',
    goBack: 'Go back',
    goHome: 'Go home',
    group: 'Group',
    hours: 'Hours',
    info: 'Information',
    infoMessage: 'This match will be played on',
    left: 'Left',
    match: 'Match',
    matches: 'Matches',
    matchPlayed: 'Matches played',
    matchPlayedMessage: 'You can edit before distributing round of 16.',
    minutes: 'Minutes',
    mp: 'MP',
    nextMatch: 'Next match',
    penalties: 'Penalties',
    pendingMatches: 'Pending Matches',
    playground: 'Playground',
    quarter: 'Quarter final',
    round: 'Round',
    round16: 'Round of 16',
    save: 'Save',
    success: 'Success',
    successMessage: 'Data restored',
    team: 'TEAM',
    thirdPlace: 'Third place',
    todayMatches: 'Today matches',
    validHours: 'Valid hours +14 | -11',
    validMinutes: 'Valid minutes 00 | 30 | 45',
    zoneError: 'Invalid time zone',
    zoneTime: 'Select your time zone',
    zoneLangMgs: 'Time zone and language saved',
  },
  ES: {
    cancel: 'Cancelar',
    championMessage: 'Campeón del mundial de Qatar 2022',
    chooseLang: 'Selecciona tu idioma',
    close: 'Cerrar',
    confirm: 'Confirmar',
    confirmDelete: 'Si, borrar',
    confirmMessage: '¿Estás seguro de restaurar los datos?',
    days: 'Días',
    delete: 'Borrar',
    deletePlayground: 'Borrar datos de simulación',
    editing: 'Editando ',
    editPlayed: 'Editar Juegos Jugados',
    endTime: 'Tiempo terminado',
    errorChangeDay:
      'Podrás cambiar el día cuando hayas guardado todos los resultados del día actual.',
    ga: 'GC',
    gd: 'DG',
    goBack: 'Volver',
    goHome: 'Volver al inicio',
    group: 'Grupo',
    hours: 'Horas',
    info: 'Información',
    infoMessage: 'Este partido se jugará el',
    left: 'Faltan',
    match: 'Partido',
    matches: 'Partidos',
    matchPlayed: 'Juegos jugados',
    matchPlayedMessage:
      'Podrás editar antes de distribuir los octavos de final.',
    minutes: 'Minutos',
    mp: 'JJ',
    nextMatch: 'Siguiente partido',
    penalties: 'Penales',
    pendingMatches: 'Partidos pendientes',
    playground: 'Simulación',
    quarter: 'Cuartos de final',
    round: 'Ronda',
    round16: 'Octavos de final',
    save: 'Guardar',
    success: 'Éxito',
    successMessage: 'Datos restaurados',
    team: 'SELECCIÓN',
    thirdPlace: 'Tercer puesto',
    todayMatches: 'Partidos del día',
    validHours: 'Horas válidas +14 | -11',
    validMinutes: 'Minutos válidos 00 | 30 | 45',
    zoneError: 'Zona horaria no válida',
    zoneTime: 'Seleciona tu zona horaria',
    zoneLangMgs: 'Idioma y zona horaria guardados',
  },
};

export default language;
