import {MatchMode} from '../types/MatchesContextProps';

type modes = MatchMode | 'trophy';
type Images = {
  [mode in modes]: {[club: string]: {title: string; file: any}};
};

const SECTIONS: Images = {
  laLiga: {
    ALM: {title: 'ALM', file: require('../assets/LaLiga/ALM.png')},
    ATH: {title: 'ATH', file: require('../assets/LaLiga/ATH.png')},
    ATL: {title: 'ATL', file: require('../assets/LaLiga/ATL.png')},
    BET: {title: 'BET', file: require('../assets/LaLiga/BET.png')},
    CAD: {title: 'CAD', file: require('../assets/LaLiga/CAD.png')},
    CEL: {title: 'CEL', file: require('../assets/LaLiga/CEL.png')},
    ELC: {title: 'ELC', file: require('../assets/LaLiga/ELC.png')},
    ESP: {title: 'ESP', file: require('../assets/LaLiga/ESP.png')},
    FCB: {title: 'FCB', file: require('../assets/LaLiga/FCB.png')},
    GET: {title: 'GET', file: require('../assets/LaLiga/GET.png')},
    GIR: {title: 'GIR', file: require('../assets/LaLiga/GIR.png')},
    MLL: {title: 'MLL', file: require('../assets/LaLiga/MLL.png')},
    OSA: {title: 'OSA', file: require('../assets/LaLiga/OSA.png')},
    RAY: {title: 'RAY', file: require('../assets/LaLiga/RAY.png')},
    RMA: {title: 'RMA', file: require('../assets/LaLiga/RMA.png')},
    RSO: {title: 'RSO', file: require('../assets/LaLiga/RSO.png')},
    SEV: {title: 'SEV', file: require('../assets/LaLiga/SEV.png')},
    VAL: {title: 'VAL', file: require('../assets/LaLiga/VAL.png')},
    VID: {title: 'VID', file: require('../assets/LaLiga/VID.png')},
    VLL: {title: 'VLL', file: require('../assets/LaLiga/VLL.png')},
  },
  premier: {
    ARS: {title: 'ARS', file: require('../assets/premier/ARS.png')},
    AVL: {title: 'AVL', file: require('../assets/premier/AVL.png')},
    BHA: {title: 'BHA', file: require('../assets/premier/BHA.png')},
    BOU: {title: 'BOU', file: require('../assets/premier/BOU.png')},
    BRE: {title: 'BRE', file: require('../assets/premier/BRE.png')},
    CHE: {title: 'CHE', file: require('../assets/premier/CHE.png')},
    CRY: {title: 'CRY', file: require('../assets/premier/CRY.png')},
    EVE: {title: 'EVE', file: require('../assets/premier/EVE.png')},
    FUL: {title: 'FUL', file: require('../assets/premier/FUL.png')},
    LEE: {title: 'LEE', file: require('../assets/premier/LEE.png')},
    LEI: {title: 'LEI', file: require('../assets/premier/LEI.png')},
    LIV: {title: 'LIV', file: require('../assets/premier/LIV.png')},
    MCI: {title: 'MCI', file: require('../assets/premier/MCI.png')},
    MUN: {title: 'MUN', file: require('../assets/premier/MUN.png')},
    NEW: {title: 'NEW', file: require('../assets/premier/NEW.png')},
    NFO: {title: 'NFO', file: require('../assets/premier/NFO.png')},
    SOU: {title: 'SOU', file: require('../assets/premier/SOU.png')},
    TOT: {title: 'TOT', file: require('../assets/premier/TOT.png')},
    WHU: {title: 'WHU', file: require('../assets/premier/WHU.png')},
    WOL: {title: 'WOL', file: require('../assets/premier/WOL.png')},
  },
  UCL: {
    ACM: {title: 'ACM', file: require('../assets/teams/ACM.png')},
    AJX: {title: 'AJX', file: require('../assets/teams/AJX.png')},
    ATL: {title: 'ATL', file: require('../assets/teams/ATL.png')},
    BEN: {title: 'BEN', file: require('../assets/teams/BEN.png')},
    BMU: {title: 'BMU', file: require('../assets/teams/BMU.png')},
    BRU: {title: 'BRU', file: require('../assets/teams/BRU.png')},
    BVB: {title: 'SEN', file: require('../assets/teams/BVB.png')},
    CEL: {title: 'CEL', file: require('../assets/teams/CEL.png')},
    CHE: {title: 'CHE', file: require('../assets/teams/CHE.png')},
    COP: {title: 'COP', file: require('../assets/teams/COP.png')},
    DIN: {title: 'DIN', file: require('../assets/teams/DIN.png')},
    FCB: {title: 'FCB', file: require('../assets/teams/FCB.png')},
    FRA: {title: 'FRA', file: require('../assets/teams/FRA.png')},
    INT: {title: 'INT', file: require('../assets/teams/INT.png')},
    JUV: {title: 'JUV', file: require('../assets/teams/JUV.png')},
    LEI: {title: 'LEI', file: require('../assets/teams/LEI.png')},
    LEV: {title: 'LEV', file: require('../assets/teams/LEV.png')},
    LIS: {title: 'LIS', file: require('../assets/teams/LIS.png')},
    LIV: {title: 'LIV', file: require('../assets/teams/LIV.png')},
    MAH: {title: 'MAH', file: require('../assets/teams/MAH.png')},
    MAR: {title: 'MAR', file: require('../assets/teams/MAR.png')},
    MCI: {title: 'MCI', file: require('../assets/teams/MCI.png')},
    NAP: {title: 'NAP', file: require('../assets/teams/NAP.png')},
    PLZ: {title: 'PLZ', file: require('../assets/teams/PLZ.png')},
    POR: {title: 'POR', file: require('../assets/teams/POR.png')},
    PSG: {title: 'PSG', file: require('../assets/teams/PSG.png')},
    RAN: {title: 'RAN', file: require('../assets/teams/RAN.png')},
    RMA: {title: 'RMA', file: require('../assets/teams/RMA.png')},
    SAL: {title: 'SAL', file: require('../assets/teams/SAL.png')},
    SEV: {title: 'SEV', file: require('../assets/teams/SEV.png')},
    SHA: {title: 'SHA', file: require('../assets/teams/SHA.png')},
    TOT: {title: 'TOT', file: require('../assets/teams/TOT.png')},
  },
  FWC: {},
  trophy: {
    laLiga: {title: 'La Liga', file: require('../assets/laLigaCup.png')},
    premier: {
      title: 'Premier League',
      file: require('../assets/premierCup.png'),
    },
    FWC: {title: 'FIFA World Cup', file: require('../assets/logoWcup.png')},
    UCL: {
      title: 'UEFA Champions League',
      file: require('../assets/UCLCup.png'),
    },
  },
};

export default SECTIONS;
